[package]
name = "logtail"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
notify = "6.1"
tokio = { version = "1.35", features = ["full"] }
anyhow = "1.0"
colored = "2.1"
